### ISSUE TITLE
graalvm-jdk-23+37.1 not support?  (apache-skywalking-java-agent-9.3.0)

### ISSUE THREAD

**Issue by martin-1120** [SkyAPM/document-cn-translation-of-skywalking#65]
INFO 2024-10-26 16:50:39.361 main PluginResourcesResolver : find skywalking plugin define in jar:file:D:\develop\apache-skywalking-java-agent-9.3.0\skywalking-agent\activations\apm-toolkit-trace-activation-9.3.0.jar!/skywalking-plugin.def 
INFO 2024-10-26 16:50:39.361 main PluginResourcesResolver : find skywalking plugin define in jar:file:D:\develop\apache-skywalking-java-agent-9.3.0\skywalking-agent\activations\apm-toolkit-webflux-activation-9.3.0.jar!/skywalking-plugin.def 
INFO 2024-10-26 16:50:41.205 main SkyWalkingAgent : Skywalking agent begin to install transformer ... 
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
Caused by: java.lang.ClassCircularityError: java/util/concurrent/ArrayBlockingQueue
	at org.apache.skywalking.apm.agent.core.logging.core.FileWriter.<init>(FileWriter.java:63)
	at org.apache.skywalking.apm.agent.core.logging.core.FileWriter.get(FileWriter.java:55)
	at org.apache.skywalking.apm.agent.core.logging.core.WriterFactory.getLogWriter(WriterFactory.java:49)
	at org.apache.skywalking.apm.agent.core.logging.core.AbstractLogger.logger(AbstractLogger.java:207)
	at org.apache.skywalking.apm.agent.core.logging.core.AbstractLogger.info(AbstractLogger.java:65)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.installClassTransformer(SkyWalkingAgent.java:156)
	at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:105)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 3 more
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message Outstanding error when calling method in invokeJavaAgentMainMethod at s\open\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 627
*** java.lang.instrument ASSERTION FAILED ***: "success" with message invokeJavaAgentMainMethod failed at s\open\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 466
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at s\open\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 429
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x6e08a9]  (no source info available)
V  [jvm.dll+0x3ed1a3]  (no source info available)
V  [jvm.dll+0x44b32a]  (no source info available)
C  [instrument.dll+0x27b1]  (no source info available)
V  [jvm.dll+0x5a199e]  (no source info available)
V  [jvm.dll+0x82d7dd]  (no source info available)
V  [jvm.dll+0x454d4e]  (no source info available)
V  [jvm.dll+0x456bd1]  (no source info available)
C  [jli.dll+0x52a3]  (no source info available)
C  [ucrtbase.dll+0x21bb2]  (no source info available)
C  [KERNEL32.DLL+0x17374]  (no source info available)
C  [ntdll.dll+0x4cc91]  (no source info available)

**Comment by martin-1120** [comment]
![image](https://github.com/user-attachments/assets/710613aa-0750-4d22-b311-2e17b8fd95d8)

**Comment by wu-sheng** [comment]
This is irrelevant.
